version: "3.3"
services:
    api:
        build: .
        ports:
            - "8085:8085"
        depends_on: 
            - db
    db:
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            APP_DB_USER: user
            APP_DB_PASS: pass
            APP_DB_NAME: online_store
        volumes:
            - ./db:/docker-entrypoint-initdb.d/