version: "3.3"
services:
    api:
        build: .
        ports:
            - "8085:8085"
        depends_on: 
            - db
    db:
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: online_store
        volumes:
            - ./docs/online_store.sql:/docker-entrypoint-initdb.d/online_store.sql
        ports: 
            - "5434:5432"